# Generated by Django 3.0.1 on 2020-01-01 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='FIELDNAME',
            new_name='phone',
        ),
    ]
